### ISSUE TITLE
Some problems i had using this plugin

### ISSUE THREAD

**Issue by Drathal** [GumpDev/componentable#1]
Hey, thanks for sharing this plugin. I wanted to try it out and had some problems.

## 1.  Components are not created

I found out that the plugin tries to create the Components inside `res://addons/componentable/components/%sComponent.gd`, but i had to create the `components` folder that was missing. After that the plugin could create components. it would be great if we could configure where this scripts are created. Outside the plugins folder would be great I think.

## 2. glowing example component

I created the glowing component script and had to find out that I have to manually create a node that is called `components`. Inside this node I created another node called `Glowing` and there I attached the glowing example script. That was not clear for me from the RERADME. 

## 3. showing component toggle buttons  

The components toggle buttons never show up. I took a look inside `componentable_inspector.gd` and found that the function `create_components_list` will create a button but that button is then never added to something. 

## 4. missleading / hard to understand part in the README

In the readme there is a part that says:
`In this example, the Component Script created will be PlayerComponent, because de class_name of the script in this node is Progress.`

That does not make sense to me. Do i miss something? I would guess that when i make a Componentable out of the Progress Node the class should me called `PgrogressComponent`   

Thanks for sharing your work. I hope that feedback helps a bit.

**Comment by gumpdev** [comment]
Hello! Thank you for providing feedback. I reviewed the code and identified some bugs, which I have fixed in the latest commits. To benefit from these fixes, kindly install the GitHub version. Please note that updating the assets on the Godot Asset Store may take some time.

The Componentable is a plugin designed to help you organize your code logic into smaller, more manageable pieces.

Here's an example of the game I'm currently working on, i have a Player that Inherits Entity, so have the Player and Entity Components
![image](https://github.com/GumpDev/componentable/assets/29582336/ec9eb823-eab9-4e2d-a6bb-fb509083f659)

Component Example:
![image](https://github.com/GumpDev/componentable/assets/29582336/b37b1525-12a1-438f-8c79-bb31289c255d)
(this component let the Entity Jump when called the jump method, and tells when the player is on floor (with jump window) and plays a sound)

**Comment by gumpdev** [comment]
If you could test the plugin again with the bug fix and provide feedback on your experience, I would be grateful!

**Comment by Drathal** [comment]
Thanks for your detailed answer and bugfix.

I tried the latest main version, followed your instructions and still have the problem that i cant see the components in the inspector.

![hOQhgSIPKS](https://github.com/GumpDev/componentable/assets/416638/ad601b5a-8ba3-45f7-aefe-597717cb9b68)

I used the `Create Componentable` Button on the Top Player node. Then i created the `glowing component`. I added a node called `components` and i added the `glowing component` as a child. (see picture)

Maybe i misunderstand how to use the plugin.

Here is a a Repo where you can see what i did: https://github.com/Drathal/components_experiment

**Comment by gumpdev** [comment]
Sorry, there was a bug in the bugfix, LOL. I accidentally sent an unfinished future change. My apologies for that. I've now updated the fix to the bugfix XD, and it should be working correctly now.

**Comment by Drathal** [comment]
Thanks again. It seems to work now :D I will play around with it in the coming days. 
![1KWYSwRJCe](https://github.com/GumpDev/componentable/assets/416638/9e753f4f-9fe6-4270-8133-e8dfa047e16d)

**Comment by gumpdev** [comment]
Yey, any feedback you can send me :D 
i want to record a video showing how to work in english and portuguese, and write better in the README 😉
